// AUTO-GENERATED from BGKnowHow bg_heroes_active.json
// Source: https://github.com/O-Nemet/bgknowhow/blob/main/bgjson/output/bg_heroes_active.json
// Total: 111 active BG heroes

import type { Tribe } from "./types";

export interface Hero {
  id: string;
  name: string;
  nameShort: string | null;
  armor: number;
  armorHighMMR: number;
  armorDuos: number | null;
  buddy: string | null;
  heroPowerText: string;
  tribe: Tribe;
  pictureSmall: string | null;
  picturePortrait: string | null;
  pictureWhole: string | null;
  pictureFull: string | null;
}

export const HEROES: Hero[] = [
  { id: "TB_BaconShop_HERO_16", name: "A. F. Kay", nameShort: "AFK", armor: 14, armorHighMMR: 14, armorDuos: 12, buddy: "Snack Vendor", heroPowerText: "Passive Skip your first two turns. Start with two minions from Tavern Tier 3.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_16_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_16_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_16_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_16.png" },
  { id: "TB_BaconShop_HERO_76", name: "Al'Akir", nameShort: "Al'Akir", armor: 13, armorHighMMR: 13, armorDuos: 10, buddy: "Spirit of Air", heroPowerText: "Passive Start of Combat: Give your left-most minion Windfury, Divine Shield, and Taunt.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_76_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_76_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_76_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_76.png" },
  { id: "TB_BaconShop_HERO_56", name: "Alexstrasza", nameShort: "Alex", armor: 7, armorHighMMR: 7, armorDuos: 7, buddy: "Vaelastrasz", heroPowerText: "Discover a Dragon. (Unlocks at Tier 4.)", tribe: "Dragons", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_56_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_56_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_56_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_56.png" },
  { id: "BG22_HERO_201", name: "Ambassador Faelin", nameShort: "Faelin", armor: 11, armorHighMMR: 11, armorDuos: 9, buddy: "Submersible Chef", heroPowerText: "Passive. Skip your first turn. Discover a Tier 2, 4, and 6 minion to get at those Tiers.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_201_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_201_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_201_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_201.png" },
  { id: "TB_BaconShop_HERO_45", name: "Arch-Villain Rafaam", nameShort: "Rafaam", armor: 12, armorHighMMR: 15, armorDuos: 10, buddy: "Loyal Henchman", heroPowerText: "Next combat, add a plain copy of the first minion you kill to your hand.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_45_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_45_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_45_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_45.png" },
  { id: "BG31_HERO_802", name: "Artanis", nameShort: "Artanis", armor: 15, armorHighMMR: 15, armorDuos: 18, buddy: null, heroPowerText: "Passive. At the start of the game, choose from 2 Protoss minions to get after you buy 14 cards.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG31_HERO_802_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG31_HERO_802_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG31_HERO_802_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG31_HERO_802.png" },
  { id: "BG22_HERO_001", name: "Bru'kan", nameShort: "Bru'kan", armor: 17, armorHighMMR: 17, armorDuos: 14, buddy: "Spirit Raptor", heroPowerText: "Choose an Element. Start of Combat: Call upon that Element.", tribe: "Elementals", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_001_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_001_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_001_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_001.png" },
  { id: "BG32_HERO_002", name: "Buttons", nameShort: "Buttons", armor: 10, armorHighMMR: 10, armorDuos: 7, buddy: null, heroPowerText: "On Turn 8, choose a Greater Trinket to buy (8 turns left!).", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG32_HERO_002_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG32_HERO_002_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG32_HERO_002_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG32_HERO_002.png" },
  { id: "TB_BaconShop_HERO_29", name: "C'Thun", nameShort: "C'Thun", armor: 7, armorHighMMR: 18, armorDuos: 15, buddy: "Tentacle of C'Thun", heroPowerText: "At end of turn, give a friendly minion +2/+1. Repeat 0 times. (Upgrades each turn!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_29_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_29_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_29_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_29.png" },
  { id: "BG26_HERO_101", name: "Cap'n Hoggarr", nameShort: "Hoggarr", armor: 10, armorHighMMR: 10, armorDuos: 8, buddy: "Shining Sailor", heroPowerText: "Passive After you buy a Pirate, gain 1 Gold.", tribe: "Pirates", pictureSmall: "https://bgknowhow.com/images/heroes/BG26_HERO_101_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG26_HERO_101_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG26_HERO_101_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG26_HERO_101.png" },
  { id: "TB_BaconShop_HERO_64", name: "Captain Eudora", nameShort: "Eudora", armor: 10, armorHighMMR: 10, armorDuos: 7, buddy: "Dagwik Stickytoe", heroPowerText: "Dig for a Golden minion! (4 Digs left.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_64_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_64_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_64_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_64.png" },
  { id: "TB_BaconShop_HERO_67", name: "Captain Hooktusk", nameShort: "Hooktusk", armor: 15, armorHighMMR: 11, armorDuos: 9, buddy: "Raging Contender", heroPowerText: "Remove a minion. Choose one from a Tier lower to get.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_67_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_67_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_67_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_67.png" },
  { id: "BG21_HERO_000", name: "Cariel Roame", nameShort: "Cariel", armor: 10, armorHighMMR: 12, armorDuos: 10, buddy: "Captain Fairmount", heroPowerText: "Give 3 friendly minions +1/+1. (After you upgrade the Tavern, choose an improvement!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG21_HERO_000_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG21_HERO_000_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG21_HERO_000_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG21_HERO_000.png" },
  { id: "TB_BaconShop_HERO_78", name: "Chenvaala", nameShort: "Chenvaala", armor: 7, armorHighMMR: 10, armorDuos: 7, buddy: "Snow Elemental", heroPowerText: "Passive After you play 3 Elementals, reduce the cost of upgrading the Tavern by (3).", tribe: "Elementals", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_78_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_78_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_78_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_78.png" },
  { id: "BGDUO_HERO_222", name: "Cho", nameShort: "Cho", armor: 14, armorHighMMR: 14, armorDuos: 14, buddy: "Halfus the Mighty", heroPowerText: "Passive. Whenever you play a Golden minion, both you and Gall get a Triple Reward. (3 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BGDUO_HERO_222_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BGDUO_HERO_222_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BGDUO_HERO_222_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BGDUO_HERO_222.png" },
  { id: "BG21_HERO_020", name: "Cookie the Cook", nameShort: "Cookie", armor: 7, armorHighMMR: 7, armorDuos: 5, buddy: "Sous Chef", heroPowerText: "Throw a minion in your pot. When you've gathered 3, Discover from their minion types. (3 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG21_HERO_020_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG21_HERO_020_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG21_HERO_020_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG21_HERO_020.png" },
  { id: "TB_BaconShop_HERO_36", name: "Dancin' Deryl", nameShort: "Deryl", armor: 10, armorHighMMR: 10, armorDuos: 8, buddy: "Asher the Haberdasher", heroPowerText: "Passive. When you play a minion, give it a +1/+1 hat that passes to a friendly minion when sold.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_36_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_36_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_36_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_36.png" },
  { id: "BG20_HERO_103", name: "Death Speaker Blackthorn", nameShort: "Blackthorn", armor: 14, armorHighMMR: 14, armorDuos: 11, buddy: "Death's Head Sage", heroPowerText: "Get 2 Blood Gems. (Twice per turn.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_103_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_103_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_103_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_103.png" },
  { id: "TB_BaconShop_HERO_52", name: "Deathwing", nameShort: "Deathwing", armor: 12, armorHighMMR: 12, armorDuos: 10, buddy: "Sinestra", heroPowerText: "Passive ALL minions have +3 Attack.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_52_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_52_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_52_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_52.png" },
  { id: "TB_BaconShop_HERO_43", name: "Dinotamer Brann", nameShort: "Brann", armor: 14, armorHighMMR: 18, armorDuos: 11, buddy: "Brann's Epic Egg", heroPowerText: "Passive. After you buy 6 Battlecry minions, get a Brann Bronzebeard. (Once per game.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_43_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_43_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_43_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_43.png" },
  { id: "BG28_HERO_801", name: "Doctor Holli'dae", nameShort: "Holli", armor: 8, armorHighMMR: 10, armorDuos: 5, buddy: "The Nine Frogs", heroPowerText: "Get a random Tavern spell.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG28_HERO_801_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG28_HERO_801_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG28_HERO_801_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG28_HERO_801.png" },
  { id: "BG22_HERO_002", name: "Drek'Thar", nameShort: "Drek", armor: 15, armorHighMMR: 15, armorDuos: 12, buddy: "Frostwolf Lieutenant", heroPowerText: "Passive Avenge (2): Give your minions +1 Attack permanently.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_002_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_002_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_002_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_002.png" },
  { id: "BG25_HERO_105", name: "E.T.C., Band Manager", nameShort: "E.T.C.", armor: 10, armorHighMMR: 10, armorDuos: 7, buddy: "Talent Scout", heroPowerText: "Discover a Buddy. (Unlocks at Tier 2.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG25_HERO_105_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG25_HERO_105_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG25_HERO_105_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG25_HERO_105.png" },
  { id: "TB_BaconShop_HERO_01", name: "Edwin VanCleef", nameShort: "Edwin", armor: 18, armorHighMMR: 18, armorDuos: 15, buddy: "SI:7 Scout", heroPowerText: "Give a minion +2/+2. Upgrades after you buy 5 cards. (5 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_01_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_01_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_01_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_01.png" },
  { id: "TB_BaconShop_HERO_42", name: "Elise Starseeker", nameShort: "Elise", armor: 12, armorHighMMR: 12, armorDuos: 10, buddy: "Jr. Navigator", heroPowerText: "Discover a minion from your Tavern tier. Costs (1) more after each use.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_42_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_42_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_42_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_42.png" },
  { id: "BG24_HERO_204", name: "Enhance-o Mechano", nameShort: "Mechano", armor: 18, armorHighMMR: 18, armorDuos: 15, buddy: "Enhance-o Medico", heroPowerText: "Passive. After each Refresh, give a minion in the Tavern Taunt, Reborn, Windfury, or Divine Shield.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG24_HERO_204_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG24_HERO_204_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG24_HERO_204_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG24_HERO_204.png" },
  { id: "BG31_HERO_006", name: "Exarch Othaar", nameShort: "Othaar", armor: 15, armorHighMMR: 15, armorDuos: 12, buddy: null, heroPowerText: "The next Tavern spell you buy costs (1) less. (Unlocks on turn 3.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG31_HERO_006_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG31_HERO_006_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG31_HERO_006_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG31_HERO_006.png" },
  { id: "BG31_HERO_003", name: "Farseer Nobundo", nameShort: "Nobundo", armor: 10, armorHighMMR: 10, armorDuos: 7, buddy: null, heroPowerText: "Get a copy of the last Tavern spell you cast. Each turn, your next Hero Power costs (1) less.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG31_HERO_003_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG31_HERO_003_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG31_HERO_003_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG31_HERO_003.png" },
  { id: "BGDUO_HERO_101", name: "Flobbidinous Floop", nameShort: "Floop", armor: 15, armorHighMMR: 15, armorDuos: 15, buddy: "Glorious Gloopling", heroPowerText: "Choose a friendly minion. Start of Combat: Transform it into your teammate's highest-Tier minion.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BGDUO_HERO_101_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BGDUO_HERO_101_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BGDUO_HERO_101_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BGDUO_HERO_101.png" },
  { id: "BG32_HERO_001", name: "Forest Lord Cenarius", nameShort: "Cenarius", armor: 10, armorHighMMR: 10, armorDuos: 10, buddy: null, heroPowerText: "Increase your maximum Gold by 1.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG32_HERO_001_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG32_HERO_001_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG32_HERO_001_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG32_HERO_001.png" },
  { id: "TB_BaconShop_HERO_74", name: "Forest Warden Omu", nameShort: "Omu", armor: 6, armorHighMMR: 6, armorDuos: 5, buddy: "Evergreen Botani", heroPowerText: "Passive After you upgrade the Tavern, gain 2 Gold this turn only.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_74_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_74_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_74_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_74.png" },
  { id: "TB_BaconShop_HERO_55", name: "Fungalmancer Flurgl", nameShort: "Flurgl", armor: 15, armorHighMMR: 15, armorDuos: 12, buddy: "Sparkfin Soothsayer", heroPowerText: "Passive. After you sell 5 minions, get a random Murloc. (5 left.)", tribe: "Murlocs", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_55_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_55_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_55_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_55.png" },
  { id: "TB_BaconShop_HERO_02", name: "Galakrond", nameShort: "Gala", armor: 14, armorHighMMR: 14, armorDuos: 11, buddy: "Apostle of Galakrond", heroPowerText: "Choose a minion in the Tavern. Then choose a higher Tier minion to replace it.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_02_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_02_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_02_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_02.png" },
  { id: "BG20_HERO_283", name: "Galewing", nameShort: "Galewing", armor: 6, armorHighMMR: 6, armorDuos: 2, buddy: "Flight Trainer", heroPowerText: "Choose a new flightpath. Complete it to get a bonus!", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_283_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_283_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_283_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_283.png" },
  { id: "BGDUO_HERO_223", name: "Gall", nameShort: "Gall", armor: 14, armorHighMMR: 14, armorDuos: 14, buddy: "Halfus the Wise", heroPowerText: "Passive. Whenever you play a Golden minion, both you and Cho get a Triple Reward. (3 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BGDUO_HERO_223_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BGDUO_HERO_223_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BGDUO_HERO_223_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BGDUO_HERO_223.png" },
  { id: "TB_BaconShop_HERO_15", name: "George the Fallen", nameShort: "George", armor: 20, armorHighMMR: 20, armorDuos: 18, buddy: "Karl the Lost", heroPowerText: "Give a minion Divine Shield.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_15_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_15_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_15_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_15.png" },
  { id: "TB_BaconShop_HERO_95", name: "Greybough", nameShort: "Grey", armor: 16, armorHighMMR: 13, armorDuos: 14, buddy: "Wandering Treant", heroPowerText: "Passive Give +1/+2 and Taunt to minions you summon during combat.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_95_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_95_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_95_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_95.png" },
  { id: "BG20_HERO_242", name: "Guff Runetotem", nameShort: "Guff", armor: 10, armorHighMMR: 10, armorDuos: 8, buddy: "Baby Kodo", heroPowerText: "Passive. After you buy 20 Tiers' worth of cards, get a Triple Reward. (205 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_242_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_242_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_242_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_242.png" },
  { id: "BG23_HERO_305", name: "Heistbaron Togwaggle", nameShort: "Togwaggle", armor: 11, armorHighMMR: 11, armorDuos: 8, buddy: "Waxadred, the Drippy", heroPowerText: "Steal all minions in the Tavern. Each turn, your next Hero Power costs (1) less.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG23_HERO_305_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG23_HERO_305_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG23_HERO_305_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG23_HERO_305.png" },
  { id: "TB_BaconShop_HERO_08", name: "Illidan Stormrage", nameShort: "Illidan", armor: 17, armorHighMMR: 17, armorDuos: 15, buddy: "Eclipsion Illidari", heroPowerText: "Passive. Start of Combat: Your left and right-most minions gain +2/+1 and attack immediately.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_08_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_08_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_08_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_08.png" },
  { id: "TB_BaconShop_HERO_28", name: "Infinite Toki", nameShort: "Toki", armor: 10, armorHighMMR: 10, armorDuos: 7, buddy: "Clockwork Assistant", heroPowerText: "Refresh the Tavern. Include two minions from a higher Tavern Tier.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_28_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_28_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_28_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_28.png" },
  { id: "BG26_HERO_102", name: "Inge, the Iron Hymn", nameShort: "Inge", armor: 6, armorHighMMR: 11, armorDuos: 8, buddy: "Solemn Serenader", heroPowerText: "Give a minion Attack equal to your Tavern Tier. (Swaps to Health next turn!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG26_HERO_102_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG26_HERO_102_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG26_HERO_102_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG26_HERO_102.png" },
  { id: "BG22_HERO_200", name: "Ini Stormcoil", nameShort: "Ini", armor: 6, armorHighMMR: 15, armorDuos: 13, buddy: "Sub Scrubber", heroPowerText: "Passive: After 9 friendly minions die, get a random Mech.", tribe: "Mechs", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_200_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_200_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_200_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_200.png" },
  { id: "TB_BaconShop_HERO_71", name: "Jandice Barov", nameShort: "Jandice", armor: 15, armorHighMMR: 15, armorDuos: 13, buddy: "Jandice's Apprentice", heroPowerText: "Swap a friendly non-golden minion with a random one in the Tavern.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_71_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_71_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_71_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_71.png" },
  { id: "BG31_HERO_801", name: "Jim Raynor", nameShort: "Jim", armor: 12, armorHighMMR: 12, armorDuos: 15, buddy: null, heroPowerText: "Passive. Start with a 2/2 Battlecruiser that adds an Upgrade to the Tavern whenever it is Refreshed.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG31_HERO_801_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG31_HERO_801_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG31_HERO_801_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG31_HERO_801.png" },
  { id: "TB_BaconShop_HERO_60", name: "Kael'thas Sunstrider", nameShort: "Kael", armor: 18, armorHighMMR: 10, armorDuos: 15, buddy: "Crimson Hand Centurion", heroPowerText: "Passive. Every third minion you play gets +1/+1 and improves this by +1/+1.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_60_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_60_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_60_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_60.png" },
  { id: "BG31_HERO_811", name: "Kerrigan, Queen of Blades", nameShort: "Kerrigan", armor: 14, armorHighMMR: 14, armorDuos: 12, buddy: null, heroPowerText: "Unlock Tier 2 Zerg. Costs (1) less each turn. Passive: Start the game with a 2/2 Larva.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG31_HERO_811_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG31_HERO_811_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG31_HERO_811_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG31_HERO_811.png" },
  { id: "TB_BaconShop_HERO_38", name: "King Mukla", nameShort: "Mukla", armor: 10, armorHighMMR: 10, armorDuos: 8, buddy: "Crazy Monkey", heroPowerText: "Passive At the start of your turn, get 2 Bananas and give everyone else one.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_38_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_38_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_38_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_38.png" },
  { id: "BG20_HERO_280", name: "Kurtrus Ashfallen", nameShort: "Kurtrus", armor: 10, armorHighMMR: 10, armorDuos: 7, buddy: "Living Nightmare", heroPowerText: "Passive. Once per turn, after you buy 3 minions, get a plain copy of one of them. (3 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_280_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_280_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_280_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_280.png" },
  { id: "BG23_HERO_304", name: "Lady Vashj", nameShort: "Vashj", armor: 16, armorHighMMR: 16, armorDuos: 13, buddy: "Coilfang Elite", heroPowerText: "Discover a Spellcraft spell of your Tier or lower. Passive: Your first one each turn is permanent.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG23_HERO_304_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG23_HERO_304_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG23_HERO_304_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG23_HERO_304.png" },
  { id: "TB_BaconShop_HERO_25", name: "Lich Baz'hial", nameShort: "Lich", armor: 18, armorHighMMR: 18, armorDuos: 15, buddy: "Unearthed Underling", heroPowerText: "Steal a card from the Tavern. Take 2 damage.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_25_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_25_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_25_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_25.png" },
  { id: "TB_BaconShop_HERO_72", name: "Lord Barov", nameShort: "Barov", armor: 19, armorHighMMR: 14, armorDuos: 12, buddy: "Barov's Apprentice", heroPowerText: "Guess which player will win their next combat. If they win, get 3 Coins.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_72_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_72_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_72_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_72.png" },
  { id: "TB_BaconShop_HERO_37", name: "Lord Jaraxxus", nameShort: "Jaraxxus", armor: 10, armorHighMMR: 19, armorDuos: 17, buddy: "Kil'rek", heroPowerText: "Choose a friendly Demon. It consumes a minion in the Tavern to gain its stats.", tribe: "Demons", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_37_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_37_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_37_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_37.png" },
  { id: "BGDUO_HERO_104", name: "Madam Goya", nameShort: "Goya", armor: 8, armorHighMMR: 8, armorDuos: 8, buddy: "Mister Chu", heroPowerText: "Pass a non-Golden minion.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BGDUO_HERO_104_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BGDUO_HERO_104_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BGDUO_HERO_104_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BGDUO_HERO_104.png" },
  { id: "TB_BaconShop_HERO_62", name: "Maiev Shadowsong", nameShort: "Maiev", armor: 18, armorHighMMR: 13, armorDuos: 10, buddy: "Shadow Warden", heroPowerText: "Choose a card in the Tavern to lock in your hand. After 2 turns, unlock it.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_62_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_62_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_62_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_62.png" },
  { id: "TB_BaconShop_HERO_58", name: "Malygos", nameShort: "Maly", armor: 14, armorHighMMR: 14, armorDuos: 12, buddy: "Nexus Lord", heroPowerText: "Replace a card with a random one of the same Tavern Tier. (Twice per turn.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_58_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_58_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_58_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_58.png" },
  { id: "BG30_HERO_304", name: "Marin the Manager", nameShort: "Marin", armor: 7, armorHighMMR: 7, armorDuos: 5, buddy: null, heroPowerText: "Passive. On Turn 5, choose a Lesser Trinket to buy. (4 turns left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG30_HERO_304_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG30_HERO_304_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG30_HERO_304_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG30_HERO_304.png" },
  { id: "BG20_HERO_202", name: "Master Nguyen", nameShort: "Panda", armor: 8, armorHighMMR: 8, armorDuos: 5, buddy: "Lei Flamepaw", heroPowerText: "Passive At the start of every turn, choose from 2 new Hero Powers.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_202_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_202_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_202_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_202.png" },
  { id: "TB_BaconShop_HERO_49", name: "Millhouse Manastorm", nameShort: "Millhouse", armor: 18, armorHighMMR: 10, armorDuos: 8, buddy: "Magnus Manastorm", heroPowerText: "Passive Minions cost 2 Gold. Refresh costs 2 Gold. Tavern Tiers cost (1) more.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_49_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_49_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_49_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_49.png" },
  { id: "TB_BaconShop_HERO_17", name: "Millificent Manastorm", nameShort: "Milli", armor: 5, armorHighMMR: 19, armorDuos: 15, buddy: "Elementium Squirrel Bomb", heroPowerText: "Passive Whenever you summon a Mech, give it +3 Attack.", tribe: "Mechs", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_17_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_17_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_17_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_17.png" },
  { id: "TB_BaconShop_HERO_70", name: "Mr. Bigglesworth", nameShort: "Cat", armor: 17, armorHighMMR: 16, armorDuos: 17, buddy: "Lil' K.T.", heroPowerText: "Passive When a player dies, Discover a minion from their warband. It keeps any enchantments.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_70_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_70_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_70_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_70.png" },
  { id: "BG23_HERO_303", name: "Murloc Holmes", nameShort: "Holmes", armor: 12, armorHighMMR: 10, armorDuos: 8, buddy: "Watfin", heroPowerText: "Look at 2 minions. Guess which one your next opponent had last combat for a Coin.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG23_HERO_303_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG23_HERO_303_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG23_HERO_303_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG23_HERO_303.png" },
  { id: "BG20_HERO_301", name: "Mutanus the Devourer", nameShort: "Mutanus", armor: 18, armorHighMMR: 18, armorDuos: 15, buddy: "Nightmare Ectoplasm", heroPowerText: "Remove a friendly minion. Spit its stats onto another. Get 1 Gold.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_301_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_301_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_301_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_301.png" },
  { id: "TB_BaconShop_HERO_93", name: "N'Zoth", nameShort: "N'Zoth", armor: 10, armorHighMMR: 10, armorDuos: 7, buddy: "Baby N'Zoth", heroPowerText: "Passive Start the game with a 2/2 Fish that gains all your Deathrattles in combat.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_93_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_93_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_93_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_93.png" },
  { id: "TB_BaconShop_HERO_57", name: "Nozdormu", nameShort: "Nozdormu", armor: 13, armorHighMMR: 13, armorDuos: 10, buddy: "Chromie", heroPowerText: "Passive Your first Refresh each turn costs (0).", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_57_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_57_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_57_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_57.png" },
  { id: "BG22_HERO_305", name: "Onyxia", nameShort: "Ony", armor: 20, armorHighMMR: 20, armorDuos: 18, buddy: "Many Whelps", heroPowerText: "Passive Avenge (4): Summon a 3/1 Whelp. It attacks immediately.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_305_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_305_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_305_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_305.png" },
  { id: "BG20_HERO_102", name: "Overlord Saurfang", nameShort: "Saurfang", armor: 18, armorHighMMR: 18, armorDuos: 15, buddy: "Dranosh Saurfang", heroPowerText: "Give a minion in the Tavern +2/+2. (Doubles every 3 turns!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_102_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_102_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_102_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_102.png" },
  { id: "BG23_HERO_201", name: "Ozumat", nameShort: "Ozu", armor: 7, armorHighMMR: 15, armorDuos: 12, buddy: "Tamuzo", heroPowerText: "Passive. When you have space in combat, summon a 2/2 Tentacle with Taunt. (Gains +1/+1 after you sell a minion!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG23_HERO_201_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG23_HERO_201_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG23_HERO_201_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG23_HERO_201.png" },
  { id: "TB_BaconShop_HERO_18", name: "Patches the Pirate", nameShort: "Patches", armor: 5, armorHighMMR: 14, armorDuos: 11, buddy: "Tuskarr Raider", heroPowerText: "Get a Pirate. After you buy a Pirate, your next Hero Power costs (1) less.", tribe: "Pirates", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_18_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_18_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_18_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_18.png" },
  { id: "TB_BaconShop_HERO_34", name: "Patchwerk", nameShort: "Patchwerk", armor: 0, armorHighMMR: 0, armorDuos: 0, buddy: "Weebomination", heroPowerText: "Passive Start with 60 Health instead of 30.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_34_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_34_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_34_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_34.png" },
  { id: "BG25_HERO_100", name: "Professor Putricide", nameShort: "Putricide", armor: 16, armorHighMMR: 16, armorDuos: 14, buddy: "Festergut", heroPowerText: "Craft a custom Undead. (3 Creations left!)", tribe: "Undead", pictureSmall: "https://bgknowhow.com/images/heroes/BG25_HERO_100_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG25_HERO_100_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG25_HERO_100_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG25_HERO_100.png" },
  { id: "TB_BaconShop_HERO_39", name: "Pyramad", nameShort: "Pyramad", armor: 17, armorHighMMR: 17, armorDuos: 14, buddy: "Titanic Guardian", heroPowerText: "Give a minion +2 Health. (Gains +1 Health each turn you don't use this!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_39_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_39_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_39_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_39.png" },
  { id: "TB_BaconShop_HERO_14", name: "Queen Wagtoggle", nameShort: "Wagtoggle", armor: 10, armorHighMMR: 15, armorDuos: 13, buddy: "Elder Taggawag", heroPowerText: "Passive. Start of Combat: Give a friendly minion of each type stats equal to their Tavern Tiers.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_14_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_14_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_14_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_14.png" },
  { id: "TB_BaconShop_HERO_11", name: "Ragnaros the Firelord", nameShort: "Ragnaros", armor: 13, armorHighMMR: 15, armorDuos: 12, buddy: "Lucifron", heroPowerText: "Passive After you kill 16 enemy minions, get Sulfuras. (16 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_11_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_11_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_11_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_11.png" },
  { id: "TB_BaconShop_HERO_75", name: "Rakanishu", nameShort: "Rakanishu", armor: 17, armorHighMMR: 17, armorDuos: 15, buddy: "Lantern Tender", heroPowerText: "Get a 'Lantern Light' that gives a minion stats equal to your Tier.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_75_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_75_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_75_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_75.png" },
  { id: "TB_BaconShop_HERO_41", name: "Reno Jackson", nameShort: "Reno", armor: 16, armorHighMMR: 16, armorDuos: 13, buddy: "Sr. Tomb Diver", heroPowerText: "Make a friendly minion Golden. (Once per game.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_41_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_41_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_41_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_41.png" },
  { id: "BG26_HERO_104", name: "Rock Master Voone", nameShort: "Voone", armor: 15, armorHighMMR: 10, armorDuos: 7, buddy: "Akali, Rock Rhino", heroPowerText: "Passive. At the end of every 3 turns, get a plain copy of the left-most card in your hand. (3 turns left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG26_HERO_104_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG26_HERO_104_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG26_HERO_104_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG26_HERO_104.png" },
  { id: "BG20_HERO_100", name: "Rokara", nameShort: "Rokara", armor: 17, armorHighMMR: 17, armorDuos: 15, buddy: "Icesnarl the Mighty", heroPowerText: "Passive. After a friendly minion kills an enemy, give it +1 Attack permanently.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_100_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_100_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_100_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_100.png" },
  { id: "BG21_HERO_010", name: "Scabbs Cutterbutter", nameShort: "Scabbs", armor: 13, armorHighMMR: 13, armorDuos: 10, buddy: "Warden Thelwater", heroPowerText: "Discover a plain copy of a minion from your next opponent's warband.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG21_HERO_010_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG21_HERO_010_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG21_HERO_010_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG21_HERO_010.png" },
  { id: "TB_BaconShop_HERO_23", name: "Shudderwock", nameShort: "Shudder", armor: 10, armorHighMMR: 5, armorDuos: 2, buddy: "Muckslinger", heroPowerText: "Trigger a friendly minion's Battlecry. (Unlocks on Turn 3.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_23_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_23_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_23_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_23.png" },
  { id: "TB_BaconShop_HERO_90", name: "Silas Darkmoon", nameShort: "Silas", armor: 8, armorHighMMR: 8, armorDuos: 5, buddy: "Burth", heroPowerText: "Passive. Darkmoon Tickets are in the Tavern! Get 3 to Discover a minion from your Tavern Tier.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_90_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_90_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_90_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_90.png" },
  { id: "TB_BaconShop_HERO_27", name: "Sindragosa", nameShort: "Sindra", armor: 18, armorHighMMR: 18, armorDuos: 16, buddy: "Thawed Champion", heroPowerText: "Freeze a card in the Tavern. Passive: At the end of your turn, Frozen minions get +2/+2.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_27_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_27_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_27_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_27.png" },
  { id: "TB_BaconShop_HERO_40", name: "Sir Finley Mrrgglton", nameShort: "Finley", armor: 12, armorHighMMR: 12, armorDuos: 10, buddy: "Maxwell, Mighty Steed", heroPowerText: "Passive At the start of the game, Discover a Hero Power.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_40_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_40_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_40_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_40.png" },
  { id: "BG24_HERO_100", name: "Sire Denathrius", nameShort: "Denathrius", armor: 11, armorHighMMR: 11, armorDuos: 8, buddy: "Shady Aristocrat", heroPowerText: "Passive. At the start of the game, choose one of two Quests.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG24_HERO_100_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG24_HERO_100_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG24_HERO_100_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG24_HERO_100.png" },
  { id: "TB_BaconShop_HERO_68", name: "Skycap'n Kragg", nameShort: "Kragg", armor: 14, armorHighMMR: 14, armorDuos: 12, buddy: "Sharkbait", heroPowerText: "Gain 1 Gold this turn. Increases each turn. (Once per game.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_68_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_68_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_68_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_68.png" },
  { id: "BG28_HERO_400", name: "Snake Eyes", nameShort: "Snake", armor: 5, armorHighMMR: 5, armorDuos: 2, buddy: "Box Cars", heroPowerText: "Roll a 6-sided die. Gain that much Gold. (Cannot be used again for that many turns!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG28_HERO_400_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG28_HERO_400_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG28_HERO_400_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG28_HERO_400.png" },
  { id: "BG21_HERO_030", name: "Sneed", nameShort: "Sneed", armor: 20, armorHighMMR: 20, armorDuos: 17, buddy: "Piloted Whirl-O-Tron", heroPowerText: "Give a minion: \\\"Deathrattle: Summon a random minion from the same Tavern Tier lower.\\\"", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG21_HERO_030_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG21_HERO_030_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG21_HERO_030_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG21_HERO_030.png" },
  { id: "BG23_HERO_306", name: "Sylvanas Windrunner", nameShort: "Sylvanas", armor: 20, armorHighMMR: 20, armorDuos: 15, buddy: "Nathanos Blightcaller", heroPowerText: "Give +3/+1 to your minions that died last combat.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG23_HERO_306_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG23_HERO_306_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG23_HERO_306_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG23_HERO_306.png" },
  { id: "BG28_HERO_800", name: "Tae'thelan Bloodwatcher", nameShort: "Bloodwatcher", armor: 18, armorHighMMR: 10, armorDuos: 15, buddy: "Reliquary Attendant", heroPowerText: "Passive Every fourth Tavern Spell you buy costs (0).", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG28_HERO_800_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG28_HERO_800_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG28_HERO_800_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG28_HERO_800.png" },
  { id: "BG20_HERO_282", name: "Tamsin Roame", nameShort: "Tamsin", armor: 10, armorHighMMR: 10, armorDuos: 8, buddy: "Monstrosity", heroPowerText: "Start of Combat: Destroy your lowest Health minion. Give its stats to your other minions.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_282_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_282_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_282_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_282.png" },
  { id: "BG22_HERO_000", name: "Tavish Stormpike", nameShort: "Tavish", armor: 15, armorHighMMR: 15, armorDuos: 13, buddy: "Crabby", heroPowerText: "Take aim! Start of Combat: Deal 3 damage to your target. (Doubles every 3 turns!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_000_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_000_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_000_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_000.png" },
  { id: "BG25_HERO_103", name: "Teron Gorefiend", nameShort: "Teron", armor: 10, armorHighMMR: 10, armorDuos: 8, buddy: "Shadowy Construct", heroPowerText: "Choose a friendly minion. Start of Combat: Destroy it. Once you have space, resummon an exact copy.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG25_HERO_103_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG25_HERO_103_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG25_HERO_103_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG25_HERO_103.png" },
  { id: "TB_BaconShop_HERO_50", name: "Tess Greymane", nameShort: "Tess", armor: 17, armorHighMMR: 17, armorDuos: 14, buddy: "Hunter of Old", heroPowerText: "Refresh the Tavern with your last opponent's warband.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_50_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_50_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_50_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_50.png" },
  { id: "TB_BaconShop_HERO_33", name: "The Curator", nameShort: "Curator", armor: 13, armorHighMMR: 13, armorDuos: 10, buddy: "Mishmash", heroPowerText: "Passive Start the game with a 2/2 Amalgam with Venomous and all minion types.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_33_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_33_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_33_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_33.png" },
  { id: "TB_BaconShop_HERO_21", name: "The Great Akazamzarak", nameShort: "Akazam", armor: 7, armorHighMMR: 7, armorDuos: 5, buddy: "Street Magician", heroPowerText: "Choose a Secret. Put it into the battlefield.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_21_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_21_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_21_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_21.png" },
  { id: "TB_BaconShop_HERO_702", name: "The Jailer", nameShort: "Jailer", armor: 15, armorHighMMR: 15, armorDuos: 13, buddy: "Mawsworn Soulkeeper", heroPowerText: "Give a minion +1/+1. Upgrades after five friendly minions die. (5 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_702_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_702_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_702_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_702.png" },
  { id: "TB_BaconShop_HERO_22", name: "The Lich King", nameShort: "Lich King", armor: 10, armorHighMMR: 10, armorDuos: 8, buddy: "Arfus", heroPowerText: "Give a friendly minion Reborn for the next combat only.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_22_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_22_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_22_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_22.png" },
  { id: "BGDUO_HERO_100", name: "The Nameless One", nameShort: "Nameless", armor: 12, armorHighMMR: 12, armorDuos: 12, buddy: "Faceless One", heroPowerText: "Passive. Start of Game: Copy your teammate's Hero Power.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BGDUO_HERO_100_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BGDUO_HERO_100_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BGDUO_HERO_100_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BGDUO_HERO_100.png" },
  { id: "TB_BaconShop_HERO_12", name: "The Rat King", nameShort: "Rat King", armor: 8, armorHighMMR: 8, armorDuos: 5, buddy: "Pigeon Lord", heroPowerText: "Discover a minion of a specific type. Swaps type each turn.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_12_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_12_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_12_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_12.png" },
  { id: "BG27_HERO_801", name: "Thorim, Stormlord", nameShort: "Thorim", armor: 15, armorHighMMR: 15, armorDuos: 12, buddy: "Veranus, Stormlord's Mount", heroPowerText: "Passive. At the start of the game, Discover a Tier 7 minion to get after you spend 65 Gold. (65 left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG27_HERO_801_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG27_HERO_801_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG27_HERO_801_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG27_HERO_801.png" },
  { id: "TB_BaconShop_HERO_94", name: "Tickatus", nameShort: "Tickatus", armor: 15, armorHighMMR: 12, armorDuos: 12, buddy: "Ticket Collector", heroPowerText: "Passive Every 4 turns, Discover a Darkmoon Prize. (3 turns left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_94_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_94_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_94_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_94.png" },
  { id: "TB_BaconShop_HERO_10", name: "Trade Prince Gallywix", nameShort: "Gallywix", armor: 10, armorHighMMR: 5, armorDuos: 3, buddy: "Bilgewater Mogul", heroPowerText: "Passive After you sell a minion, get 1 extra Gold next turn. (Can exceed 10.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_10_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_10_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_10_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_10.png" },
  { id: "BG22_HERO_003", name: "Vanndar Stormpike", nameShort: "Vanndar", armor: 18, armorHighMMR: 18, armorDuos: 15, buddy: "Stormpike Lieutenant", heroPowerText: "Passive Avenge (2): Give your minions +1 Health permanently.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_003_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_003_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_003_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_003.png" },
  { id: "BG22_HERO_004", name: "Varden Dawngrasp", nameShort: "Varden", armor: 15, armorHighMMR: 15, armorDuos: 13, buddy: "Varden's Aquarrior", heroPowerText: "Passive. After the Tavern is Refreshed, copy his highest Tier minion and Freeze them both.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG22_HERO_004_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG22_HERO_004_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG22_HERO_004_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG22_HERO_004.png" },
  { id: "BG20_HERO_201", name: "Vol'jin", nameShort: "Vol'jin", armor: 15, armorHighMMR: 15, armorDuos: 13, buddy: "Master Gadrin", heroPowerText: "Choose 2 minions. They gain each other's Attack until next turn.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_201_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_201_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_201_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_201.png" },
  { id: "BG20_HERO_101", name: "Xyrella", nameShort: "Xyrella", armor: 10, armorHighMMR: 8, armorDuos: 5, buddy: "Baby Elekk", heroPowerText: "Choose a minion in the Tavern to add to your hand. Set its stats to 2.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG20_HERO_101_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG20_HERO_101_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG20_HERO_101_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG20_HERO_101.png" },
  { id: "TB_BaconShop_HERO_92", name: "Y'Shaarj", nameShort: "Y'Shaarj", armor: 18, armorHighMMR: 18, armorDuos: 16, buddy: "Baby Y'Shaarj", heroPowerText: "Start of Combat: Summon and get a random minion from your Tavern Tier.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_92_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_92_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_92_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_92.png" },
  { id: "TB_BaconShop_HERO_35", name: "Yogg-Saron, Hope's End", nameShort: "Yogg", armor: 14, armorHighMMR: 14, armorDuos: 11, buddy: "Acolyte of Yogg-Saron", heroPowerText: "Add a random minion in the Tavern to your hand. Give it +1/+1.", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_35_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_35_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_35_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_35.png" },
  { id: "TB_BaconShop_HERO_53", name: "Ysera", nameShort: "Ysera", armor: 5, armorHighMMR: 10, armorDuos: 14, buddy: "Valithria Dreamwalker", heroPowerText: "Passive The Tavern always offers an extra Dragon whenever it is Refreshed.", tribe: "Dragons", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_53_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_53_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_53_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_53.png" },
  { id: "TB_BaconShop_HERO_91", name: "Zephrys, the Great", nameShort: "Zephrys", armor: 17, armorHighMMR: 17, armorDuos: 15, buddy: "Phyresz", heroPowerText: "If you have two copies of a minion, find the third. (3 Wishes left!)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_91_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_91_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/TB_BaconShop_HERO_91_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/TB_BaconShop_HERO_91.png" },
  { id: "BG31_HERO_005", name: "Zerek, Master Cloner", nameShort: "Zerek", armor: 17, armorHighMMR: 17, armorDuos: 14, buddy: null, heroPowerText: "Summon an exact copy of a friendly minion. (Once per game.)", tribe: "All", pictureSmall: "https://bgknowhow.com/images/heroes/BG31_HERO_005_render_80.webp", picturePortrait: "https://bgknowhow.com/images/heroes/BG31_HERO_005_portrait.png", pictureWhole: "https://bgknowhow.com/images/heroes/BG31_HERO_005_big.webp", pictureFull: "https://art.hearthstonejson.com/v1/render/latest/enUS/512x/BG31_HERO_005.png" },
];

export function getAllHeroes(): Hero[] {
  return [...HEROES].sort((a, b) => a.name.localeCompare(b.name));
}

export function getHeroById(id: string): Hero | undefined {
  return HEROES.find((h) => h.id === id);
}
